// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/local_store/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 273186095957995459),
    name: 'AppSettingsEntity',
    lastPropertyId: const obx_int.IdUid(21, 6426574414698199161),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6151654332411899331),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4870439738623681667),
        name: 'runtimeMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2689516764677915094),
        name: 'answerModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 823185486034734900),
        name: 'extractionModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7708937587965630938),
        name: 'groundednessModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1134803171024918487),
        name: 'embeddingModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3480948655704252683),
        name: 'deleteOpenAiFilesAfterProcessing',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8183084045610728334),
        name: 'groundednessCheckEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7429739853728458970),
        name: 'retrievalLimit',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4974685060174619275),
        name: 'minimumSimilarity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1667832177506930805),
        name: 'activeProvider',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1071311406819407556),
        name: 'openAiAnswerModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4170766179930431758),
        name: 'openAiExtractionModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8692620291714524788),
        name: 'openAiGroundednessModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 9049035414435053789),
        name: 'openAiEmbeddingModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8971881285814950610),
        name: 'geminiAnswerModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 58424644763178777),
        name: 'geminiExtractionModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2148224121699403889),
        name: 'geminiGroundednessModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 7871929055330479097),
        name: 'geminiEmbeddingModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 9075641455202048823),
        name: 'voiceMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6426574414698199161),
        name: 'voiceLocale',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5820756277407453353),
    name: 'ChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(10, 3834798967049747048),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1239454640375525512),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1481141814642834213),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 7104952893324674412),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3479927539872829088),
        name: 'threadPublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7573213395152556153),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4823379341156395219),
        name: 'sender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8088500521866011778),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8436095980946832476),
        name: 'createdAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7874787853865112690),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8847774522795458262),
        name: 'refusalReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 853991707939113464),
        name: 'hasValidationWarning',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3834798967049747048),
        name: 'warningText',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 971375568611496488),
    name: 'ChatThreadEntity',
    lastPropertyId: const obx_int.IdUid(5, 6408779749700127604),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5754319873734364330),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6799272137713985053),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3321809719620362846),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1766271467511992035),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9066549958708376142),
        name: 'createdAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6408779749700127604),
        name: 'updatedAtMillis',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5900457559156482000),
    name: 'ChunkEmbeddingEntity',
    lastPropertyId: const obx_int.IdUid(6, 6413981021026356748),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6556681889606672404),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4474674955037704815),
        name: 'sourceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 402113048354199375),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 14984194624066992),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6456488215719235560),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 5204830089907731185),
        hnswParams: obx_int.ModelHnswParams(dimensions: 3072, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1640760635370399152),
        name: 'model',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6413981021026356748),
        name: 'createdAtMillis',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2835970348795291073),
    name: 'CitationEntity',
    lastPropertyId: const obx_int.IdUid(9, 8182112017704924585),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8676979959152515161),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8522252519736762089),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 5381871697716329763),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4126409159189696406),
        name: 'messagePublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 4909169522223840535),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4323778465106549661),
        name: 'sourceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 6188981945236455199),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5940150031219381010),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4676993803606790384),
        name: 'sourceLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4146089689161092435),
        name: 'documentPublicId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7736663679092013391),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8182112017704924585),
        name: 'excerpt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 9012920818068651330),
    name: 'DocumentChunkEntity',
    lastPropertyId: const obx_int.IdUid(7, 6184607323443707496),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5206250045140841812),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1628053356831854107),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 5968809646666895316),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8638837129045034888),
        name: 'documentPublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 7237428048621886160),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5697290722411591078),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7701346108871482881),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1063090330926866476),
        name: 'sectionTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6184607323443707496),
        name: 'sourceRectJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1380656129107944180),
    name: 'FlowchartEdgeEntity',
    lastPropertyId: const obx_int.IdUid(8, 4415689705722391472),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7388369756181216034),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7479145569352808172),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 7686138038136824239),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2758892422504889195),
        name: 'flowchartPublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 110937085109048497),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6242049840779187114),
        name: 'fromNodePublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 5229898192111188069),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 681085543244684237),
        name: 'toNodePublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 9153381040733100664),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2167330231405372595),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8344310248615376906),
        name: 'validationState',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(15, 8736082283656258084),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4415689705722391472),
        name: 'rejectionReason',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5224985862224986658),
    name: 'FlowchartEntity',
    lastPropertyId: const obx_int.IdUid(7, 6900534565950075870),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8420234669820551985),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7905891858769764136),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(16, 6889876402607771318),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4641309630125911843),
        name: 'documentPublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(17, 3529231849908932421),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5673228613423518257),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3430430742670588819),
        name: 'validationState',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(18, 4907545513841456243),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2042409891874930596),
        name: 'sourceRectJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6900534565950075870),
        name: 'extractionConfidence',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 8189989850069876083),
    name: 'FlowchartNodeEntity',
    lastPropertyId: const obx_int.IdUid(8, 7047686114766363714),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3809450008516868147),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5946470280488378442),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(19, 8403852432553652729),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6469772974842693295),
        name: 'flowchartPublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(20, 5562207467015221186),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5772003807181961769),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2805332220168215896),
        name: 'validationState',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(21, 9108477623800392369),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3082480403551302333),
        name: 'rejectionReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5003843109152425586),
        name: 'positionX',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7047686114766363714),
        name: 'positionY',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 3835227895295506301),
    name: 'KnowledgeDocumentEntity',
    lastPropertyId: const obx_int.IdUid(9, 3427317077375592081),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4678741659041516704),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 88649406242999106),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(22, 3670981183639069265),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3964283411306006332),
        name: 'filename',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9144691853718936988),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6719209927533881780),
        name: 'sizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3342914424157633728),
        name: 'importedAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4880907321942637558),
        name: 'processingState',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(23, 4726824978689913267),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8596181767817437087),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3427317077375592081),
        name: 'openAiFileId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 7309319277825706740),
    name: 'ProcessingJobEntity',
    lastPropertyId: const obx_int.IdUid(7, 3924378542852389945),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5820039981620720752),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3025497669755157454),
        name: 'publicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(24, 3177623305391312732),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6678687660226771157),
        name: 'documentPublicId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(25, 263402484209870658),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7538025831003002037),
        name: 'state',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(26, 6263710456666240614),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8117369331642433838),
        name: 'createdAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8327205169060449651),
        name: 'updatedAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3924378542852389945),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 7309319277825706740),
    lastIndexId: const obx_int.IdUid(26, 6263710456666240614),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettingsEntity: obx_int.EntityDefinition<AppSettingsEntity>(
      model: _entities[0],
      toOneRelations: (AppSettingsEntity object) => [],
      toManyRelations: (AppSettingsEntity object) => {},
      getId: (AppSettingsEntity object) => object.id,
      setId: (AppSettingsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettingsEntity object, fb.Builder fbb) {
        final runtimeModeOffset = fbb.writeString(object.runtimeMode);
        final answerModelOffset = fbb.writeString(object.answerModel);
        final extractionModelOffset = fbb.writeString(object.extractionModel);
        final groundednessModelOffset = fbb.writeString(
          object.groundednessModel,
        );
        final embeddingModelOffset = fbb.writeString(object.embeddingModel);
        final activeProviderOffset = fbb.writeString(object.activeProvider);
        final openAiAnswerModelOffset = fbb.writeString(
          object.openAiAnswerModel,
        );
        final openAiExtractionModelOffset = fbb.writeString(
          object.openAiExtractionModel,
        );
        final openAiGroundednessModelOffset = fbb.writeString(
          object.openAiGroundednessModel,
        );
        final openAiEmbeddingModelOffset = fbb.writeString(
          object.openAiEmbeddingModel,
        );
        final geminiAnswerModelOffset = fbb.writeString(
          object.geminiAnswerModel,
        );
        final geminiExtractionModelOffset = fbb.writeString(
          object.geminiExtractionModel,
        );
        final geminiGroundednessModelOffset = fbb.writeString(
          object.geminiGroundednessModel,
        );
        final geminiEmbeddingModelOffset = fbb.writeString(
          object.geminiEmbeddingModel,
        );
        final voiceModeOffset = fbb.writeString(object.voiceMode);
        final voiceLocaleOffset = fbb.writeString(object.voiceLocale);
        fbb.startTable(22);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, runtimeModeOffset);
        fbb.addOffset(2, answerModelOffset);
        fbb.addOffset(3, extractionModelOffset);
        fbb.addOffset(4, groundednessModelOffset);
        fbb.addOffset(5, embeddingModelOffset);
        fbb.addBool(6, object.deleteOpenAiFilesAfterProcessing);
        fbb.addBool(7, object.groundednessCheckEnabled);
        fbb.addInt64(8, object.retrievalLimit);
        fbb.addFloat64(9, object.minimumSimilarity);
        fbb.addOffset(10, activeProviderOffset);
        fbb.addOffset(11, openAiAnswerModelOffset);
        fbb.addOffset(12, openAiExtractionModelOffset);
        fbb.addOffset(13, openAiGroundednessModelOffset);
        fbb.addOffset(14, openAiEmbeddingModelOffset);
        fbb.addOffset(15, geminiAnswerModelOffset);
        fbb.addOffset(16, geminiExtractionModelOffset);
        fbb.addOffset(17, geminiGroundednessModelOffset);
        fbb.addOffset(18, geminiEmbeddingModelOffset);
        fbb.addOffset(19, voiceModeOffset);
        fbb.addOffset(20, voiceLocaleOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final runtimeModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final activeProviderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final openAiAnswerModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final openAiExtractionModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final openAiGroundednessModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final openAiEmbeddingModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final geminiAnswerModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final geminiExtractionModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final geminiGroundednessModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final geminiEmbeddingModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final answerModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final extractionModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final groundednessModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final embeddingModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final deleteOpenAiFilesAfterProcessingParam = const fb.BoolReader()
            .vTableGet(buffer, rootOffset, 16, false);
        final groundednessCheckEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final retrievalLimitParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final minimumSimilarityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final voiceModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final voiceLocaleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final object = AppSettingsEntity(
          id: idParam,
          runtimeMode: runtimeModeParam,
          activeProvider: activeProviderParam,
          openAiAnswerModel: openAiAnswerModelParam,
          openAiExtractionModel: openAiExtractionModelParam,
          openAiGroundednessModel: openAiGroundednessModelParam,
          openAiEmbeddingModel: openAiEmbeddingModelParam,
          geminiAnswerModel: geminiAnswerModelParam,
          geminiExtractionModel: geminiExtractionModelParam,
          geminiGroundednessModel: geminiGroundednessModelParam,
          geminiEmbeddingModel: geminiEmbeddingModelParam,
          answerModel: answerModelParam,
          extractionModel: extractionModelParam,
          groundednessModel: groundednessModelParam,
          embeddingModel: embeddingModelParam,
          deleteOpenAiFilesAfterProcessing:
              deleteOpenAiFilesAfterProcessingParam,
          groundednessCheckEnabled: groundednessCheckEnabledParam,
          retrievalLimit: retrievalLimitParam,
          minimumSimilarity: minimumSimilarityParam,
          voiceMode: voiceModeParam,
          voiceLocale: voiceLocaleParam,
        );

        return object;
      },
    ),
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
      model: _entities[1],
      toOneRelations: (ChatMessageEntity object) => [],
      toManyRelations: (ChatMessageEntity object) => {},
      getId: (ChatMessageEntity object) => object.id,
      setId: (ChatMessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final threadPublicIdOffset = fbb.writeString(object.threadPublicId);
        final senderOffset = fbb.writeString(object.sender);
        final textOffset = fbb.writeString(object.text);
        final statusOffset = object.status == null
            ? null
            : fbb.writeString(object.status!);
        final refusalReasonOffset = object.refusalReason == null
            ? null
            : fbb.writeString(object.refusalReason!);
        final warningTextOffset = object.warningText == null
            ? null
            : fbb.writeString(object.warningText!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, threadPublicIdOffset);
        fbb.addOffset(3, senderOffset);
        fbb.addOffset(4, textOffset);
        fbb.addInt64(5, object.createdAtMillis);
        fbb.addOffset(6, statusOffset);
        fbb.addOffset(7, refusalReasonOffset);
        fbb.addBool(8, object.hasValidationWarning);
        fbb.addOffset(9, warningTextOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final threadPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final senderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final refusalReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final hasValidationWarningParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final warningTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = ChatMessageEntity(
          id: idParam,
          publicId: publicIdParam,
          threadPublicId: threadPublicIdParam,
          sender: senderParam,
          text: textParam,
          createdAtMillis: createdAtMillisParam,
          status: statusParam,
          refusalReason: refusalReasonParam,
          hasValidationWarning: hasValidationWarningParam,
          warningText: warningTextParam,
        );

        return object;
      },
    ),
    ChatThreadEntity: obx_int.EntityDefinition<ChatThreadEntity>(
      model: _entities[2],
      toOneRelations: (ChatThreadEntity object) => [],
      toManyRelations: (ChatThreadEntity object) => {},
      getId: (ChatThreadEntity object) => object.id,
      setId: (ChatThreadEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatThreadEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.createdAtMillis);
        fbb.addInt64(4, object.updatedAtMillis);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final updatedAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = ChatThreadEntity(
          id: idParam,
          publicId: publicIdParam,
          title: titleParam,
          createdAtMillis: createdAtMillisParam,
          updatedAtMillis: updatedAtMillisParam,
        );

        return object;
      },
    ),
    ChunkEmbeddingEntity: obx_int.EntityDefinition<ChunkEmbeddingEntity>(
      model: _entities[3],
      toOneRelations: (ChunkEmbeddingEntity object) => [],
      toManyRelations: (ChunkEmbeddingEntity object) => {},
      getId: (ChunkEmbeddingEntity object) => object.id,
      setId: (ChunkEmbeddingEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChunkEmbeddingEntity object, fb.Builder fbb) {
        final sourceIdOffset = fbb.writeString(object.sourceId);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final vectorOffset = object.vector == null
            ? null
            : fbb.writeListFloat32(object.vector!);
        final modelOffset = fbb.writeString(object.model);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceIdOffset);
        fbb.addOffset(2, sourceTypeOffset);
        fbb.addOffset(3, vectorOffset);
        fbb.addOffset(4, modelOffset);
        fbb.addInt64(5, object.createdAtMillis);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final vectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final modelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ChunkEmbeddingEntity(
          id: idParam,
          sourceId: sourceIdParam,
          sourceType: sourceTypeParam,
          vector: vectorParam,
          model: modelParam,
          createdAtMillis: createdAtMillisParam,
        );

        return object;
      },
    ),
    CitationEntity: obx_int.EntityDefinition<CitationEntity>(
      model: _entities[4],
      toOneRelations: (CitationEntity object) => [],
      toManyRelations: (CitationEntity object) => {},
      getId: (CitationEntity object) => object.id,
      setId: (CitationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CitationEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final messagePublicIdOffset = fbb.writeString(object.messagePublicId);
        final sourceIdOffset = fbb.writeString(object.sourceId);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final sourceLabelOffset = fbb.writeString(object.sourceLabel);
        final documentPublicIdOffset = object.documentPublicId == null
            ? null
            : fbb.writeString(object.documentPublicId!);
        final excerptOffset = object.excerpt == null
            ? null
            : fbb.writeString(object.excerpt!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, messagePublicIdOffset);
        fbb.addOffset(3, sourceIdOffset);
        fbb.addOffset(4, sourceTypeOffset);
        fbb.addOffset(5, sourceLabelOffset);
        fbb.addOffset(6, documentPublicIdOffset);
        fbb.addInt64(7, object.pageNumber);
        fbb.addOffset(8, excerptOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final messagePublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final sourceLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final documentPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final pageNumberParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final excerptParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = CitationEntity(
          id: idParam,
          publicId: publicIdParam,
          messagePublicId: messagePublicIdParam,
          sourceId: sourceIdParam,
          sourceType: sourceTypeParam,
          sourceLabel: sourceLabelParam,
          documentPublicId: documentPublicIdParam,
          pageNumber: pageNumberParam,
          excerpt: excerptParam,
        );

        return object;
      },
    ),
    DocumentChunkEntity: obx_int.EntityDefinition<DocumentChunkEntity>(
      model: _entities[5],
      toOneRelations: (DocumentChunkEntity object) => [],
      toManyRelations: (DocumentChunkEntity object) => {},
      getId: (DocumentChunkEntity object) => object.id,
      setId: (DocumentChunkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunkEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final documentPublicIdOffset = fbb.writeString(object.documentPublicId);
        final textOffset = fbb.writeString(object.text);
        final sectionTitleOffset = object.sectionTitle == null
            ? null
            : fbb.writeString(object.sectionTitle!);
        final sourceRectJsonOffset = object.sourceRectJson == null
            ? null
            : fbb.writeString(object.sourceRectJson!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, documentPublicIdOffset);
        fbb.addOffset(3, textOffset);
        fbb.addInt64(4, object.pageNumber);
        fbb.addOffset(5, sectionTitleOffset);
        fbb.addOffset(6, sourceRectJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final documentPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final pageNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final sectionTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final sourceRectJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = DocumentChunkEntity(
          id: idParam,
          publicId: publicIdParam,
          documentPublicId: documentPublicIdParam,
          text: textParam,
          pageNumber: pageNumberParam,
          sectionTitle: sectionTitleParam,
          sourceRectJson: sourceRectJsonParam,
        );

        return object;
      },
    ),
    FlowchartEdgeEntity: obx_int.EntityDefinition<FlowchartEdgeEntity>(
      model: _entities[6],
      toOneRelations: (FlowchartEdgeEntity object) => [],
      toManyRelations: (FlowchartEdgeEntity object) => {},
      getId: (FlowchartEdgeEntity object) => object.id,
      setId: (FlowchartEdgeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FlowchartEdgeEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final flowchartPublicIdOffset = fbb.writeString(
          object.flowchartPublicId,
        );
        final fromNodePublicIdOffset = fbb.writeString(object.fromNodePublicId);
        final toNodePublicIdOffset = fbb.writeString(object.toNodePublicId);
        final labelOffset = fbb.writeString(object.label);
        final validationStateOffset = fbb.writeString(object.validationState);
        final rejectionReasonOffset = object.rejectionReason == null
            ? null
            : fbb.writeString(object.rejectionReason!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, flowchartPublicIdOffset);
        fbb.addOffset(3, fromNodePublicIdOffset);
        fbb.addOffset(4, toNodePublicIdOffset);
        fbb.addOffset(5, labelOffset);
        fbb.addOffset(6, validationStateOffset);
        fbb.addOffset(7, rejectionReasonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final flowchartPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final fromNodePublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final toNodePublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final validationStateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final rejectionReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = FlowchartEdgeEntity(
          id: idParam,
          publicId: publicIdParam,
          flowchartPublicId: flowchartPublicIdParam,
          fromNodePublicId: fromNodePublicIdParam,
          toNodePublicId: toNodePublicIdParam,
          label: labelParam,
          validationState: validationStateParam,
          rejectionReason: rejectionReasonParam,
        );

        return object;
      },
    ),
    FlowchartEntity: obx_int.EntityDefinition<FlowchartEntity>(
      model: _entities[7],
      toOneRelations: (FlowchartEntity object) => [],
      toManyRelations: (FlowchartEntity object) => {},
      getId: (FlowchartEntity object) => object.id,
      setId: (FlowchartEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FlowchartEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final documentPublicIdOffset = fbb.writeString(object.documentPublicId);
        final validationStateOffset = fbb.writeString(object.validationState);
        final sourceRectJsonOffset = object.sourceRectJson == null
            ? null
            : fbb.writeString(object.sourceRectJson!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, documentPublicIdOffset);
        fbb.addInt64(3, object.pageNumber);
        fbb.addOffset(4, validationStateOffset);
        fbb.addOffset(5, sourceRectJsonOffset);
        fbb.addFloat64(6, object.extractionConfidence);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final documentPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final pageNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final validationStateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final sourceRectJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final extractionConfidenceParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final object = FlowchartEntity(
          id: idParam,
          publicId: publicIdParam,
          documentPublicId: documentPublicIdParam,
          pageNumber: pageNumberParam,
          validationState: validationStateParam,
          sourceRectJson: sourceRectJsonParam,
          extractionConfidence: extractionConfidenceParam,
        );

        return object;
      },
    ),
    FlowchartNodeEntity: obx_int.EntityDefinition<FlowchartNodeEntity>(
      model: _entities[8],
      toOneRelations: (FlowchartNodeEntity object) => [],
      toManyRelations: (FlowchartNodeEntity object) => {},
      getId: (FlowchartNodeEntity object) => object.id,
      setId: (FlowchartNodeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FlowchartNodeEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final flowchartPublicIdOffset = fbb.writeString(
          object.flowchartPublicId,
        );
        final labelOffset = fbb.writeString(object.label);
        final validationStateOffset = fbb.writeString(object.validationState);
        final rejectionReasonOffset = object.rejectionReason == null
            ? null
            : fbb.writeString(object.rejectionReason!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, flowchartPublicIdOffset);
        fbb.addOffset(3, labelOffset);
        fbb.addOffset(4, validationStateOffset);
        fbb.addOffset(5, rejectionReasonOffset);
        fbb.addFloat64(6, object.positionX);
        fbb.addFloat64(7, object.positionY);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final flowchartPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final validationStateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final rejectionReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final positionXParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final positionYParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = FlowchartNodeEntity(
          id: idParam,
          publicId: publicIdParam,
          flowchartPublicId: flowchartPublicIdParam,
          label: labelParam,
          validationState: validationStateParam,
          rejectionReason: rejectionReasonParam,
          positionX: positionXParam,
          positionY: positionYParam,
        );

        return object;
      },
    ),
    KnowledgeDocumentEntity: obx_int.EntityDefinition<KnowledgeDocumentEntity>(
      model: _entities[9],
      toOneRelations: (KnowledgeDocumentEntity object) => [],
      toManyRelations: (KnowledgeDocumentEntity object) => {},
      getId: (KnowledgeDocumentEntity object) => object.id,
      setId: (KnowledgeDocumentEntity object, int id) {
        object.id = id;
      },
      objectToFB: (KnowledgeDocumentEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final filenameOffset = fbb.writeString(object.filename);
        final localPathOffset = fbb.writeString(object.localPath);
        final processingStateOffset = fbb.writeString(object.processingState);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        final openAiFileIdOffset = object.openAiFileId == null
            ? null
            : fbb.writeString(object.openAiFileId!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, filenameOffset);
        fbb.addOffset(3, localPathOffset);
        fbb.addInt64(4, object.sizeBytes);
        fbb.addInt64(5, object.importedAtMillis);
        fbb.addOffset(6, processingStateOffset);
        fbb.addOffset(7, errorMessageOffset);
        fbb.addOffset(8, openAiFileIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final filenameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sizeBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final importedAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final processingStateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final openAiFileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = KnowledgeDocumentEntity(
          id: idParam,
          publicId: publicIdParam,
          filename: filenameParam,
          localPath: localPathParam,
          sizeBytes: sizeBytesParam,
          importedAtMillis: importedAtMillisParam,
          processingState: processingStateParam,
          errorMessage: errorMessageParam,
          openAiFileId: openAiFileIdParam,
        );

        return object;
      },
    ),
    ProcessingJobEntity: obx_int.EntityDefinition<ProcessingJobEntity>(
      model: _entities[10],
      toOneRelations: (ProcessingJobEntity object) => [],
      toManyRelations: (ProcessingJobEntity object) => {},
      getId: (ProcessingJobEntity object) => object.id,
      setId: (ProcessingJobEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProcessingJobEntity object, fb.Builder fbb) {
        final publicIdOffset = fbb.writeString(object.publicId);
        final documentPublicIdOffset = fbb.writeString(object.documentPublicId);
        final stateOffset = fbb.writeString(object.state);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicIdOffset);
        fbb.addOffset(2, documentPublicIdOffset);
        fbb.addOffset(3, stateOffset);
        fbb.addInt64(4, object.createdAtMillis);
        fbb.addInt64(5, object.updatedAtMillis);
        fbb.addOffset(6, errorMessageOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final documentPublicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final stateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final updatedAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = ProcessingJobEntity(
          id: idParam,
          publicId: publicIdParam,
          documentPublicId: documentPublicIdParam,
          state: stateParam,
          createdAtMillis: createdAtMillisParam,
          updatedAtMillis: updatedAtMillisParam,
          errorMessage: errorMessageParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettingsEntity] entity fields to define ObjectBox queries.
class AppSettingsEntity_ {
  /// See [AppSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[0].properties[0],
  );

  /// See [AppSettingsEntity.runtimeMode].
  static final runtimeMode = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[1],
  );

  /// See [AppSettingsEntity.answerModel].
  static final answerModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[2],
  );

  /// See [AppSettingsEntity.extractionModel].
  static final extractionModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[3],
  );

  /// See [AppSettingsEntity.groundednessModel].
  static final groundednessModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[4],
  );

  /// See [AppSettingsEntity.embeddingModel].
  static final embeddingModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[5],
  );

  /// See [AppSettingsEntity.deleteOpenAiFilesAfterProcessing].
  static final deleteOpenAiFilesAfterProcessing =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[0].properties[6]);

  /// See [AppSettingsEntity.groundednessCheckEnabled].
  static final groundednessCheckEnabled =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[0].properties[7]);

  /// See [AppSettingsEntity.retrievalLimit].
  static final retrievalLimit = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[0].properties[8],
  );

  /// See [AppSettingsEntity.minimumSimilarity].
  static final minimumSimilarity = obx.QueryDoubleProperty<AppSettingsEntity>(
    _entities[0].properties[9],
  );

  /// See [AppSettingsEntity.activeProvider].
  static final activeProvider = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[10],
  );

  /// See [AppSettingsEntity.openAiAnswerModel].
  static final openAiAnswerModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[11],
  );

  /// See [AppSettingsEntity.openAiExtractionModel].
  static final openAiExtractionModel =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[0].properties[12]);

  /// See [AppSettingsEntity.openAiGroundednessModel].
  static final openAiGroundednessModel =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[0].properties[13]);

  /// See [AppSettingsEntity.openAiEmbeddingModel].
  static final openAiEmbeddingModel =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[0].properties[14]);

  /// See [AppSettingsEntity.geminiAnswerModel].
  static final geminiAnswerModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[15],
  );

  /// See [AppSettingsEntity.geminiExtractionModel].
  static final geminiExtractionModel =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[0].properties[16]);

  /// See [AppSettingsEntity.geminiGroundednessModel].
  static final geminiGroundednessModel =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[0].properties[17]);

  /// See [AppSettingsEntity.geminiEmbeddingModel].
  static final geminiEmbeddingModel =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[0].properties[18]);

  /// See [AppSettingsEntity.voiceMode].
  static final voiceMode = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[19],
  );

  /// See [AppSettingsEntity.voiceLocale].
  static final voiceLocale = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[20],
  );
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.id].
  static final id = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[0],
  );

  /// See [ChatMessageEntity.publicId].
  static final publicId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[1],
  );

  /// See [ChatMessageEntity.threadPublicId].
  static final threadPublicId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[2],
  );

  /// See [ChatMessageEntity.sender].
  static final sender = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[3],
  );

  /// See [ChatMessageEntity.text].
  static final text = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[4],
  );

  /// See [ChatMessageEntity.createdAtMillis].
  static final createdAtMillis = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[5],
  );

  /// See [ChatMessageEntity.status].
  static final status = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[6],
  );

  /// See [ChatMessageEntity.refusalReason].
  static final refusalReason = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[7],
  );

  /// See [ChatMessageEntity.hasValidationWarning].
  static final hasValidationWarning =
      obx.QueryBooleanProperty<ChatMessageEntity>(_entities[1].properties[8]);

  /// See [ChatMessageEntity.warningText].
  static final warningText = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[9],
  );
}

/// [ChatThreadEntity] entity fields to define ObjectBox queries.
class ChatThreadEntity_ {
  /// See [ChatThreadEntity.id].
  static final id = obx.QueryIntegerProperty<ChatThreadEntity>(
    _entities[2].properties[0],
  );

  /// See [ChatThreadEntity.publicId].
  static final publicId = obx.QueryStringProperty<ChatThreadEntity>(
    _entities[2].properties[1],
  );

  /// See [ChatThreadEntity.title].
  static final title = obx.QueryStringProperty<ChatThreadEntity>(
    _entities[2].properties[2],
  );

  /// See [ChatThreadEntity.createdAtMillis].
  static final createdAtMillis = obx.QueryIntegerProperty<ChatThreadEntity>(
    _entities[2].properties[3],
  );

  /// See [ChatThreadEntity.updatedAtMillis].
  static final updatedAtMillis = obx.QueryIntegerProperty<ChatThreadEntity>(
    _entities[2].properties[4],
  );
}

/// [ChunkEmbeddingEntity] entity fields to define ObjectBox queries.
class ChunkEmbeddingEntity_ {
  /// See [ChunkEmbeddingEntity.id].
  static final id = obx.QueryIntegerProperty<ChunkEmbeddingEntity>(
    _entities[3].properties[0],
  );

  /// See [ChunkEmbeddingEntity.sourceId].
  static final sourceId = obx.QueryStringProperty<ChunkEmbeddingEntity>(
    _entities[3].properties[1],
  );

  /// See [ChunkEmbeddingEntity.sourceType].
  static final sourceType = obx.QueryStringProperty<ChunkEmbeddingEntity>(
    _entities[3].properties[2],
  );

  /// See [ChunkEmbeddingEntity.vector].
  static final vector = obx.QueryHnswProperty<ChunkEmbeddingEntity>(
    _entities[3].properties[3],
  );

  /// See [ChunkEmbeddingEntity.model].
  static final model = obx.QueryStringProperty<ChunkEmbeddingEntity>(
    _entities[3].properties[4],
  );

  /// See [ChunkEmbeddingEntity.createdAtMillis].
  static final createdAtMillis = obx.QueryIntegerProperty<ChunkEmbeddingEntity>(
    _entities[3].properties[5],
  );
}

/// [CitationEntity] entity fields to define ObjectBox queries.
class CitationEntity_ {
  /// See [CitationEntity.id].
  static final id = obx.QueryIntegerProperty<CitationEntity>(
    _entities[4].properties[0],
  );

  /// See [CitationEntity.publicId].
  static final publicId = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[1],
  );

  /// See [CitationEntity.messagePublicId].
  static final messagePublicId = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[2],
  );

  /// See [CitationEntity.sourceId].
  static final sourceId = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[3],
  );

  /// See [CitationEntity.sourceType].
  static final sourceType = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[4],
  );

  /// See [CitationEntity.sourceLabel].
  static final sourceLabel = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[5],
  );

  /// See [CitationEntity.documentPublicId].
  static final documentPublicId = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[6],
  );

  /// See [CitationEntity.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<CitationEntity>(
    _entities[4].properties[7],
  );

  /// See [CitationEntity.excerpt].
  static final excerpt = obx.QueryStringProperty<CitationEntity>(
    _entities[4].properties[8],
  );
}

/// [DocumentChunkEntity] entity fields to define ObjectBox queries.
class DocumentChunkEntity_ {
  /// See [DocumentChunkEntity.id].
  static final id = obx.QueryIntegerProperty<DocumentChunkEntity>(
    _entities[5].properties[0],
  );

  /// See [DocumentChunkEntity.publicId].
  static final publicId = obx.QueryStringProperty<DocumentChunkEntity>(
    _entities[5].properties[1],
  );

  /// See [DocumentChunkEntity.documentPublicId].
  static final documentPublicId = obx.QueryStringProperty<DocumentChunkEntity>(
    _entities[5].properties[2],
  );

  /// See [DocumentChunkEntity.text].
  static final text = obx.QueryStringProperty<DocumentChunkEntity>(
    _entities[5].properties[3],
  );

  /// See [DocumentChunkEntity.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<DocumentChunkEntity>(
    _entities[5].properties[4],
  );

  /// See [DocumentChunkEntity.sectionTitle].
  static final sectionTitle = obx.QueryStringProperty<DocumentChunkEntity>(
    _entities[5].properties[5],
  );

  /// See [DocumentChunkEntity.sourceRectJson].
  static final sourceRectJson = obx.QueryStringProperty<DocumentChunkEntity>(
    _entities[5].properties[6],
  );
}

/// [FlowchartEdgeEntity] entity fields to define ObjectBox queries.
class FlowchartEdgeEntity_ {
  /// See [FlowchartEdgeEntity.id].
  static final id = obx.QueryIntegerProperty<FlowchartEdgeEntity>(
    _entities[6].properties[0],
  );

  /// See [FlowchartEdgeEntity.publicId].
  static final publicId = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[1],
  );

  /// See [FlowchartEdgeEntity.flowchartPublicId].
  static final flowchartPublicId = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[2],
  );

  /// See [FlowchartEdgeEntity.fromNodePublicId].
  static final fromNodePublicId = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[3],
  );

  /// See [FlowchartEdgeEntity.toNodePublicId].
  static final toNodePublicId = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[4],
  );

  /// See [FlowchartEdgeEntity.label].
  static final label = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[5],
  );

  /// See [FlowchartEdgeEntity.validationState].
  static final validationState = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[6],
  );

  /// See [FlowchartEdgeEntity.rejectionReason].
  static final rejectionReason = obx.QueryStringProperty<FlowchartEdgeEntity>(
    _entities[6].properties[7],
  );
}

/// [FlowchartEntity] entity fields to define ObjectBox queries.
class FlowchartEntity_ {
  /// See [FlowchartEntity.id].
  static final id = obx.QueryIntegerProperty<FlowchartEntity>(
    _entities[7].properties[0],
  );

  /// See [FlowchartEntity.publicId].
  static final publicId = obx.QueryStringProperty<FlowchartEntity>(
    _entities[7].properties[1],
  );

  /// See [FlowchartEntity.documentPublicId].
  static final documentPublicId = obx.QueryStringProperty<FlowchartEntity>(
    _entities[7].properties[2],
  );

  /// See [FlowchartEntity.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<FlowchartEntity>(
    _entities[7].properties[3],
  );

  /// See [FlowchartEntity.validationState].
  static final validationState = obx.QueryStringProperty<FlowchartEntity>(
    _entities[7].properties[4],
  );

  /// See [FlowchartEntity.sourceRectJson].
  static final sourceRectJson = obx.QueryStringProperty<FlowchartEntity>(
    _entities[7].properties[5],
  );

  /// See [FlowchartEntity.extractionConfidence].
  static final extractionConfidence = obx.QueryDoubleProperty<FlowchartEntity>(
    _entities[7].properties[6],
  );
}

/// [FlowchartNodeEntity] entity fields to define ObjectBox queries.
class FlowchartNodeEntity_ {
  /// See [FlowchartNodeEntity.id].
  static final id = obx.QueryIntegerProperty<FlowchartNodeEntity>(
    _entities[8].properties[0],
  );

  /// See [FlowchartNodeEntity.publicId].
  static final publicId = obx.QueryStringProperty<FlowchartNodeEntity>(
    _entities[8].properties[1],
  );

  /// See [FlowchartNodeEntity.flowchartPublicId].
  static final flowchartPublicId = obx.QueryStringProperty<FlowchartNodeEntity>(
    _entities[8].properties[2],
  );

  /// See [FlowchartNodeEntity.label].
  static final label = obx.QueryStringProperty<FlowchartNodeEntity>(
    _entities[8].properties[3],
  );

  /// See [FlowchartNodeEntity.validationState].
  static final validationState = obx.QueryStringProperty<FlowchartNodeEntity>(
    _entities[8].properties[4],
  );

  /// See [FlowchartNodeEntity.rejectionReason].
  static final rejectionReason = obx.QueryStringProperty<FlowchartNodeEntity>(
    _entities[8].properties[5],
  );

  /// See [FlowchartNodeEntity.positionX].
  static final positionX = obx.QueryDoubleProperty<FlowchartNodeEntity>(
    _entities[8].properties[6],
  );

  /// See [FlowchartNodeEntity.positionY].
  static final positionY = obx.QueryDoubleProperty<FlowchartNodeEntity>(
    _entities[8].properties[7],
  );
}

/// [KnowledgeDocumentEntity] entity fields to define ObjectBox queries.
class KnowledgeDocumentEntity_ {
  /// See [KnowledgeDocumentEntity.id].
  static final id = obx.QueryIntegerProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[0],
  );

  /// See [KnowledgeDocumentEntity.publicId].
  static final publicId = obx.QueryStringProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[1],
  );

  /// See [KnowledgeDocumentEntity.filename].
  static final filename = obx.QueryStringProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[2],
  );

  /// See [KnowledgeDocumentEntity.localPath].
  static final localPath = obx.QueryStringProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[3],
  );

  /// See [KnowledgeDocumentEntity.sizeBytes].
  static final sizeBytes = obx.QueryIntegerProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[4],
  );

  /// See [KnowledgeDocumentEntity.importedAtMillis].
  static final importedAtMillis =
      obx.QueryIntegerProperty<KnowledgeDocumentEntity>(
        _entities[9].properties[5],
      );

  /// See [KnowledgeDocumentEntity.processingState].
  static final processingState =
      obx.QueryStringProperty<KnowledgeDocumentEntity>(
        _entities[9].properties[6],
      );

  /// See [KnowledgeDocumentEntity.errorMessage].
  static final errorMessage = obx.QueryStringProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[7],
  );

  /// See [KnowledgeDocumentEntity.openAiFileId].
  static final openAiFileId = obx.QueryStringProperty<KnowledgeDocumentEntity>(
    _entities[9].properties[8],
  );
}

/// [ProcessingJobEntity] entity fields to define ObjectBox queries.
class ProcessingJobEntity_ {
  /// See [ProcessingJobEntity.id].
  static final id = obx.QueryIntegerProperty<ProcessingJobEntity>(
    _entities[10].properties[0],
  );

  /// See [ProcessingJobEntity.publicId].
  static final publicId = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[10].properties[1],
  );

  /// See [ProcessingJobEntity.documentPublicId].
  static final documentPublicId = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[10].properties[2],
  );

  /// See [ProcessingJobEntity.state].
  static final state = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[10].properties[3],
  );

  /// See [ProcessingJobEntity.createdAtMillis].
  static final createdAtMillis = obx.QueryIntegerProperty<ProcessingJobEntity>(
    _entities[10].properties[4],
  );

  /// See [ProcessingJobEntity.updatedAtMillis].
  static final updatedAtMillis = obx.QueryIntegerProperty<ProcessingJobEntity>(
    _entities[10].properties[5],
  );

  /// See [ProcessingJobEntity.errorMessage].
  static final errorMessage = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[10].properties[6],
  );
}
