import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const app = await readFile(new URL('../assets/app.js', import.meta.url), 'utf8');
const discovery = await readFile(new URL('../assets/explore-discovery.js', import.meta.url), 'utf8');
const screen = await readFile(new URL('../screens/explore.html', import.meta.url), 'utf8');
const inlineCss = await readFile(new URL('../assets/explore-galaxy-inline.css', import.meta.url), 'utf8');
const orb = await readFile(new URL('../assets/explore-galaxy-orb.js', import.meta.url), 'utf8');
const planetData = await readFile(new URL('../assets/explore/planet-data.js', import.meta.url), 'utf8');
const planetVisuals = await readFile(new URL('../assets/explore/planet-visuals.js', import.meta.url), 'utf8');
const edgeLayer = await readFile(new URL('../assets/djinn-edge-layer.js', import.meta.url), 'utf8');

assert.match(discovery, /\['overview', 'Áttekintés'\]/);
assert.match(discovery, /\['concepts', 'Fogalmak'\]/);
assert.match(discovery, /\['connections', 'Kapcsolatok'\]/);
assert.match(discovery, /tab\.dataset\.exploreTab = id/);
assert.match(discovery, /activate\('overview'\)/);
assert.doesNotMatch(discovery, /insertAdjacentHTML\('afterend', DISCOVERY_TEMPLATE\)/);
assert.match(screen, /data-explore-discovery/);
assert.doesNotMatch(screen, /data-galaxy-anchor/);
assert.match(screen, /data-explore-panel="overview"/);
assert.match(screen, /data-explore-panel="concepts"/);
assert.match(screen, /data-explore-panel="connections"/);
assert.match(screen, /Mai felfedezés/);
assert.match(screen, /explore-galaxy-stats/);
assert.match(screen, /128<\/strong> atom/);
assert.match(screen, /7 jegyzet · 3 közös chunk/);
assert.match(screen, /Folytasd, ahol abbahagytad/);
assert.match(screen, /Érdekes kapcsolatok/);
assert.match(screen, /Tudásutak/);
assert.match(screen, /Növekvő témák/);
assert.match(screen, /Fogalmak, amelyek most összeérnek/);
assert.match(screen, /Kapcsolatok, amelyek új kontextust nyitnak/);
assert.match(screen, /data-explore-focus="oxygen_delivery"/);
assert.match(screen, /data-explore-focus="pao2"/);
assert.match(screen, /Koppints egy fogalomkártyára/);
assert.match(screen, /Legerősebb/);
assert.match(screen, /Közösségek között/);
assert.match(screen, /data-route="workspace-topic-connections"/);

const overview = screen.slice(
  screen.indexOf('data-explore-panel="overview"'),
  screen.indexOf('data-explore-panel="concepts"'),
);
const concepts = screen.slice(
  screen.indexOf('data-explore-panel="concepts"'),
  screen.indexOf('data-explore-panel="connections"'),
);
const connections = screen.slice(screen.indexOf('data-explore-panel="connections"'));
assert.doesNotMatch(overview, /Érdekes kapcsolatok|Növekvő témák/);
assert.match(overview, /id="explore-featured-path"/);
assert.match(concepts, /id="explore-growing-topics"/);
assert.match(connections, /id="explore-knowledge-paths"/);
assert.match(index, /assets\/explore-discovery\.css\?rev=5/);
assert.match(index, /assets\/explore-galaxy-inline\.css\?rev=4/);
assert.match(index, /assets\/styles\.css\?rev=146/);
assert.match(index, /assets\/app\.js\?rev=273/);
assert.match(app, /initExpandableGalaxyOrb \} from '\.\/explore-galaxy-orb\.js\?rev=239';/);
assert.match(app, /import \{ initExploreDiscovery \} from '\.\/explore-discovery\.js\?rev=3';/);
assert.match(app, /onConceptFocus: \(nodeId, trigger\) => galaxyOrb\?\.focusConcept\(nodeId, trigger\)/);
assert.match(app, /normalized === 'explore'[\s\S]*initExploreDiscovery\(root,/);
assert.match(app, /galaxySlot\?\.replaceChildren\(galaxyRoot\)/);
assert.match(inlineCss, /#explore-galaxy-orb-root\.is-inline/);
assert.match(inlineCss, /\.explore-galaxy-slot[\s\S]*height: 230px/);
assert.match(orb, /layer\.dataset\.state = 'expanded'/);
assert.doesNotMatch(orb, /data-galaxy-action="collapse"/);
assert.doesNotMatch(orb, /galaxy-orb-trigger/);
assert.match(orb, /class="galaxy-orb-title">Tudásgalaxis<\/span>/);
assert.match(orb, /data-galaxy-action="fullscreen"/);
assert.match(orb, /value="stars-only">Stars Only/);
assert.doesNotMatch(orb, /value="sun-only">Sun Only/);
assert.match(orb, /requestFullscreen/);
assert.match(orb, /fullscreenchange/);
assert.match(orb, /aria-pressed/);
assert.match(orb, /setGalaxyFullscreen/);
assert.match(orb, /document\.exitFullscreen/);
assert.match(orb, /data-galaxy-action="fullscreen"/);
assert.match(inlineCss, /explore-galaxy-slot/);
const styles = await readFile(new URL('../assets/styles.css', import.meta.url), 'utf8');
assert.match(styles, /expandable-galaxy-orb\.is-fullscreen/);
assert.match(styles, /galaxy-orb-morph:fullscreen/);
assert.match(styles, /galaxy-orb-label-layer/);
assert.match(styles, /galaxy-orb-label\.is-focus/);
assert.match(orb, /data-galaxy-variant="v1"/);
assert.match(orb, /data-galaxy-variant="v2"/);
assert.match(orb, /DJINN_ORB_V2/);
assert.match(orb, /data-galaxy-variant="v3"/);
assert.match(orb, /data-galaxy-variant="v4"/);
assert.match(orb, /data-galaxy-variant="v5"/);
assert.match(orb, /DJINN_ORB_V3/);
assert.match(orb, /DJINN_ORB_V4/);
assert.match(orb, /DJINN_ORB_V5/);
assert.match(orb, /galaxy-orb-label-layer/);
assert.match(orb, /function v5LabelCandidates\(\)/);
assert.match(orb, /function labelsOverlap\(a, b, padding = 6\)/);
assert.match(orb, /function refreshV5Labels\(\)/);
assert.match(orb, /planet-label-lod\.js\?rev=1/);
assert.match(orb, /function v5LabelLodState\(\)/);
assert.match(orb, /city-selection-arcs\.js\?rev=9/);
assert.match(orb, /SURFACE_SELECTION_ARC_PROFILE/);
assert.match(orb, /function applyCitySelection\(cityId\)/);
assert.match(orb, /function clearCitySelection\(reason = 'clear'\)/);
assert.doesNotMatch(orb, /function v5ArcPoints\(edge, peakAltitude, segments = 64\)/);
assert.doesNotMatch(orb, /function v5ScreenNodeRecords\(\)/);
assert.doesNotMatch(orb, /function safeV5ArcAltitude\(edge, records\)/);
assert.doesNotMatch(orb, /if \(focusedNode\) return 7/);
assert.doesNotMatch(orb, /if \(distance > 2\.55\) return 3/);
assert.doesNotMatch(orb, /if \(distance < 1\.68\) return 8/);
assert.match(planetData, /V3_ATOM_COUNT = 700/);
assert.match(orb, /data-v3-layout/);
assert.match(orb, /spherical-force/);
assert.match(orb, /community-caps/);
assert.match(orb, /community-arc/);
assert.match(orb, /community-adaptive/);
assert.match(orb, /community-overkill/);
assert.match(orb, /data-v3-edge-diagnostic/);
assert.match(orb, /data-v3-bridge-renderer/);
assert.match(orb, /value="native-auto"/);
assert.match(orb, /value="native-weighted"/);
assert.match(orb, /nativeBridgeData/);
assert.match(orb, /renderBridges: true/);
assert.match(orb, /arcAltitudeAutoScale/);
assert.match(orb, /arcDashAnimateTime/);
assert.match(orb, /FF933C/);
assert.match(orb, /data-v3-edge-enabled/);
assert.match(orb, /data-v3-edge-back/);
assert.match(orb, /data-v4-local-edges/);
assert.match(orb, /data-v4-remote-edges/);
assert.match(orb, /value="background"/);
assert.match(orb, /value="structure"/);
assert.match(orb, /value="bridge"/);
assert.match(orb, /value="white"/);
assert.match(orb, /v3DiagnosticMode/);
assert.match(orb, /missing-node/);
assert.match(orb, /created \$\{selected\.length\}/);
assert.match(orb, /overkillArcAltitude/);
assert.match(planetData, /V3_PHYSICS_EDGES, overkill \? 10 : 2/);
assert.match(planetData, /arcPass: 'background'/);
assert.match(planetData, /arcPass: 'structure'/);
assert.match(planetData, /arcPass: 'bridge'/);
assert.match(orb, /pathResolution\(isV5Variant\(\)\s*\? SURFACE_SELECTION_ARC_PROFILE\.pathResolution/);
assert.match(orb, /arcCircularResolution\(\(nativeBridgeMode \|\| isV5Variant\(\)\) \? 4/);
assert.match(orb, /edge\.arcPass === 'background'\) return v3DiagnosticMode === 'white' \? \.12 : null/);
assert.match(orb, /edge\.arcPass === 'bridge'[\s\S]*Math\.min\(\.35/);
assert.match(orb, /Math\.max\(\.12, focusStroke \* 1\.5\)/);
assert.match(orb, /:\s*null;/);
assert.match(orb, /adaptiveArcAltitude/);
assert.match(planetData, /physicsOnly/);
assert.match(orb, /largeArcStyle/);
assert.match(orb, /DJINN_ORB_V2\.structure/);
assert.match(orb, /djinn-edge-layer\.js\?rev=6/);
assert.match(orb, /DjinnEdgeLayer/);
assert.match(orb, /djinnEdgeLayer\.setVisible\(false\)/);
assert.match(orb, /globe\.arcsData\(\[/);
assert.match(orb, /v4FocusArc/);
assert.match(orb, /setEdgeVisibility/);
assert.match(orb, /function isV5Variant\(\)/);
assert.match(orb, /if \(isV5Variant\(\)\) return focusedNode \? v5FocusArcs\(\) : \[\];/);
assert.match(planetData, /V5_IDLE_EDGE_BLUEPRINT/);
assert.match(orb, /V5_FOCUS_NO_ZOOM/);
assert.match(orb, /if \(isV5Variant\(\) && V5_FOCUS_NO_ZOOM\) \{[\s\S]*refreshEdges\(\);[\s\S]*return;/);
assert.match(orb, /clearPlanetSelectionArcs\(\{ globe, trace: planetSignalTrace/);
assert.match(orb, /v5Mode/);
assert.match(orb, /function v5FocusArcs\(\)/);
assert.match(orb, /const selection = activeV5CitySelection\(\)/);
assert.match(orb, /selectedSurfaceArcEndpointAltitude/);
assert.match(orb, /isSurfaceSelectionArc\(edge\)/);
assert.match(orb, /const transition = applyCitySelection\(node\.id\)/);
assert.match(orb, /action: transition\.action/);
assert.match(orb, /function scheduleV5LabelProjection\(\)/);
assert.match(orb, /globe\.scene\(\)\.updateMatrixWorld\?\.\(true\);[\s\S]*camera\.updateMatrixWorld\?\.\(true\);[\s\S]*refreshV5Labels\(\);/);
assert.match(orb, /globe\.controls\(\)\.addEventListener\('change', v5LabelProjectionListener\);/);
assert.match(orb, /removeEventListener\('change', v5LabelProjectionListener\)/);
assert.match(orb, /DJINN_ORB_V5\.focus/);
assert.match(orb, /focusedNode && !isRelated \? DJINN_ORB_V5\.atomDim/);
assert.match(orb, /isRelated \? \.62 : \.06/);
assert.match(orb, /v5Mode \? \.12/);
assert.match(orb, /isRelated \? 1\.5 : \.25/);
assert.match(orb, /if \(isSurfaceSelectionArc\(edge\)\) return surfaceSelectionArcProfile\(edge\)\.stroke/);
assert.match(orb, /isSurfaceSelectionArc\(edge\) \? 0/);
assert.match(orb, /function arcEndpointAltitude\(edge, endpoint\)/);
assert.match(orb, /arcStartAltitude\(\(arc\) => selectedSurfaceArcEndpointAltitude\(arc, 'start'\)\)/);
assert.match(orb, /arcEndAltitude\(\(arc\) => selectedSurfaceArcEndpointAltitude\(arc, 'end'\)\)/);
assert.match(orb, /visualRadius \/ globeRadius/);
assert.match(orb, /const measuredRadius = Number\(worldScale\?\.x \|\| 0\)/);
assert.match(orb, /measuredRadius > 0/);
assert.match(orb, /\+ \.018/);
assert.doesNotMatch(orb, /function nodeArcGeo\(node\)/);
assert.doesNotMatch(orb, /\bv5FocusArc\b/);
assert.doesNotMatch(orb, /v5NativeArc/);
assert.doesNotMatch(orb, /v5ArcAltitude/);
assert.match(orb, /isV3Family\(\) && globe/);
assert.match(orb, /const facing = worldPosition\(node\)\.normalize\(\)\.dot\(cameraDirection\)/);
assert.match(orb, /isV5Variant\(\) \|\| facing > -\.12/);
assert.match(orb, /data\.sphere\.material\.depthTest = !v5Mode/);
assert.match(orb, /data\.sphere\.material\.depthWrite = !v5Mode/);
assert.match(orb, /data\.sphere\.renderOrder = v5Mode \? 3 : 0/);
assert.match(planetVisuals, /export const VARIANT_PROFILES = Object\.freeze\(/);
assert.match(orb, /function switchOrbVariant\(nextVariant\)/);
assert.match(orb, /function resetFocusForVariantSwitch\(\)/);
assert.match(orb, /switchOrbVariant\(requestedVariant\)/);
assert.match(orb, /variantProfile\.layout/);
assert.match(orb, /rebindPlanetObjects\(/);
assert.match(orb, /const material = nodeMaterial\(node\)/);
assert.match(orb, /if \(isV5Variant\(\)\) \{[\s\S]*material\.color\.set\(DJINN_ORB_V5\.atom\)/);
assert.match(orb, /globe\.showGlobe\?\.\(true\)/);
assert.match(planetVisuals, /space: DJINN_ORB_V4\.space/);
assert.match(planetVisuals, /planet: DJINN_ORB_V4\.planet/);
assert.match(orb, /ambientLight\.color\.set\(isV5Variant\(\) \? '#255D82'/);
assert.match(orb, /keyLight\.color\.set\(isV5Variant\(\) \? '#FFF0D1'/);
assert.match(orb, /function v5NodeHemisphereProfile\(facing\)/);
assert.match(orb, /v5NodeHemisphereProfile\(facing\)/);
assert.match(orb, /v5Profile\.opacity/);
assert.match(planetData, /weightedDegreeMap/);
assert.match(planetData, /quantile-tiers/);
assert.match(planetData, /V5_TIER_MULTIPLIERS/);
assert.match(orb, /baseImportanceScale \* perspectiveScale \* interactionScale/);
assert.match(orb, /data\.collisionRadius/);
assert.match(orb, /data\.hitRadius/);
assert.match(orb, /data-v5-size-rank-debug/);
assert.match(orb, /data-v5-clamp-debug/);
assert.match(orb, /data-v5-size-stats/);
assert.match(orb, /v5BridgeRingGeometry/);
assert.match(orb, /const related = focusedNode \? connectedTo\(focusedNode\.id\) : null/);
assert.match(orb, /const isRelated = related\?\.has\(nodeId\)/);
assert.match(planetVisuals, /focused: Object\.freeze\(\{ sphereOpacity: 1, emissiveIntensity: \.98, glowMultiplier: 2\.8/);
assert.match(planetVisuals, /related: Object\.freeze\(\{ sphereOpacity: \.86, emissiveIntensity: \.62, glowMultiplier: 1\.5/);
assert.match(planetVisuals, /dimmed: Object\.freeze\(\{ sphereOpacity: \.07, emissiveIntensity: \.018, glowMultiplier: \.06/);
assert.match(orb, /focusedNode\?\.id === node\.id/);
assert.match(orb, /focusedNode = null/);
assert.match(edgeLayer, /export class DjinnEdgeLayer/);
assert.match(edgeLayer, /this\.planetGraphRoot\.add\(this\.group\)/);
assert.match(edgeLayer, /forceGraph\.linkVisibility\?\.\(false\)/);
assert.match(edgeLayer, /postProcessingComposer/);
assert.match(edgeLayer, /ShaderMaterial/);
assert.match(edgeLayer, /slerpDirection/);
assert.match(edgeLayer, /background/);
assert.match(edgeLayer, /structure/);
assert.match(edgeLayer, /bridge/);
assert.match(edgeLayer, /setEdgeVisibility/);
assert.match(edgeLayer, /localEdgesVisible/);
assert.match(edgeLayer, /remoteEdgesVisible/);
assert.match(edgeLayer, /BufferGeometry/);
assert.doesNotMatch(edgeLayer, /new THREE\.WebGLRenderer/);
assert.doesNotMatch(edgeLayer, /requestAnimationFrame/);

console.log('explore discovery dashboard OK');
